---
- name: Package prerequisites for Perl
  apt: name={{ item }} state=present
  with_items:
    - make
    - gcc
    - curl
    - perl-doc
    - libmodule-build-perl

- name: Install cpanminus
  shell: curl -L http://cpanmin.us | perl - App::cpanminus

- name: Update ExtUtils::MakeMaker
  cpanm: ExtUtils::MakeMaker

- name: Update File::Spec
  cpanm: File::Spec

- name: Update File::Find::Rule
  cpanm: File::Find::Rule

- name: Update File::Basename
  cpanm: File::Basename

- name: Update NetAddr::IP
  cpanm: NetAddr::IP


