---
- name: Package prerequisites for Perl
  apt: name=make state=present
  with_items:
    - make
    - gcc
    - curl
    - perl-doc
    - libmodule-build-perl

- name: Install cpanminus
  shell: curl -L http://cpanmin.us | perl - App::cpanminus
  register: install_cpanm
  changed_when: "'is up to date' not in install_cpanm.stdout"

- name: Install Carton
  shell: cpanm --dev Carton
  register: install_carton
  changed_when: "'is up to date' not in install_carton.stdout"

- name: Install URI
  shell: cpanm URI
  register: install_uri
  changed_when: "'is up to date' not in install_uri.stdout"